apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cscs-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.ingress.kubernetes.io/router.middlewares: default-traefik-redirect-to-https@kubernetescrd,default-traefik-ratelimit@kubernetescrd,default-traefik-hsts@kubernetescrd
spec:
  tls:
    - secretName: redmine-tls
      hosts:
        - task.cscs.asia
  rules:
  - host: task.cscs.asia
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: redmine
              port:
                number: 80