apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - postgres-service.yaml
  - redmine.yaml
  - redmine-service.yaml
configMapGenerator:
  - name: environment
    envs:
      - ./postgresql.env
  - name: configuration
    files:
      - ./configuration.yml
      - ./zh-TW.yml
