apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres.yaml
- postgres-service.yaml
- redmine.yaml
- redmine-service.yaml
configMapGenerator:
- envs:
  - ./postgresql.env
  name: environment
- files:
  - ./additional_environment.rb
  - ./configuration.yml
  - ./zh-TW.yml
  name: configuration
images:
- name: redmine
  newName: local-redmine