apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.2
          args: ["-c", "log_statement=all", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql"]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: environment
          volumeMounts:
            - name: postgre-pv
              subPath: data
              mountPath: /var/lib/postgresql/data
            - name: postgre-pv
              subPath: log
              mountPath: /var/log/postgresql
      volumes:
        - name: postgre-pv
          persistentVolumeClaim:
            claimName: postgres-pv-claim