apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "6000m"
              memory: "6000Mi"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /login
              port: http
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            httpGet:
              path: /login
              port: http
              scheme: HTTP
          envFrom:
            - configMapRef:
                name: environment
          volumeMounts:
            - name: redmine-yml
              subPath: configuration.yml
              mountPath: /usr/src/redmine/configuration.yml
            - name: redmine-yml
              subPath: zh-TW.yml
              mountPath: /usr/src/redmine/zh-TW.yml
            - name: redmine-yml
              subPath: additional_environment.rb
              mountPath: /usr/src/redmine/additional_environment.rb
            - name: redmine-pv
              subPath: files
              mountPath: /usr/src/redmine/files
            - name: redmine-pv
              subPath: plugins/openpgp
              mountPath: /usr/src/redmine/plugins/openpgp
            - subPath: gnupg
              name: redmine-pv
              mountPath: /home/redmine/.gnupg
      volumes:
        - name: redmine-pv
          persistentVolumeClaim:
            claimName: redmine-pv-claim
        - name: redmine-yml
          configMap:
            name: configuration